# Site settings
title: "Paulo Bomfim currículo"
description: "Currículo de Paulo H."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Paulo Bomfim"
resume_title:                   "Engenheiro de Software"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "contact@phbomfim.dev"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+55 71 9 9963 2241"
resume_contact_address:         "Salvador, Brasil"

resume_header_contact_info:     "Salvador, Brasil • +55 71 9 9963 2241 • contact@phbomfim.dev"
display_header_contact_info:    "true"

resume_header_intro: "<p>Desenvolvendo softwares desde 2017.
                         Forte experiência com design e arquitetura, metodologias e softwares open source.
                         Conhecimento em PHP, Ruby, JavaScript, C++ e outras linguagens.
                         Atualmente trabalhando em desenvolvimento web.
                      </p>" 

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/phbomfim/"
  #resume_twitter_url:           "http://twitter.com/phbomfimdev"
  #resume_dribbble_url:          ""
  #resume_facebook_url:          "https://www.facebook.com/PauloBonfa/"
  #resume_linkedin_url:          "https://www.linkedin.com/in/phbomfim/"
  #resume_instagram_url:         "https://www.instagram.com/phbomfimm/"
  #resume_website_url:           "http://phbomfim.dev"
  #resume_medium_url:            ""
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
